--- # original credits https://github.com/StarterSquad/prudentia/blob/master/prudentia/tasks/add-sudo-user.yml

  - name: Hint
    ansible.builtin.debug:
      msg: "Creating deploy user {{ theuser }}:{{ thegroup }} with home directory {{ home }}"
    tags:
     - deployer

  - name: Hint
    ansible.builtin.debug:
      msg: "IMPORTANT! IF YOU PROVIDE PASS FOR DEPLOYMENT USER - PROVIDE IT HASHED,"
  - name: Hint
    ansible.builtin.debug:
      msg: "POSSIBLE FILTER -  | password_hash('sha512') "

  - name: Deploy User | Dependencies
    ansible.builtin.package:
      name: "sudo"
      state: "present"
    retries: 3
    register: result
    until: not result.failed
    become: true
    tags:
     - deployer


  - name: Deploy User | Creating group
    ansible.builtin.group:
      name: "{{ thegroup }}"
      state: present
    become: true
    tags:
     - deployer

  - name: Deploy User | Creating user
    ansible.builtin.user:
      name: "{{ theuser }}"
      home: "{{ home }}"
      state: "present"
      shell: "/bin/bash"
      generate_ssh_key: "yes"
      group: "{{ thegroup }}"
      groups: "{{ deploy_user_group }}"
      password: "{{ thepassword | default(omit) }}"
    become: true
    tags:
      - deployer

  - name: Deploy User | Check regular user key presence
    ansible.builtin.stat:
      path: "/home/{{ ansible_user_id }}/.ssh/authorized_keys"
    become: true
    when: option_copy_initial_authorized_keys
    register: check_authorized_keys
    tags:
     - deployer

  - name: Deploy User | Copy authorized_keys from {{ ansible_user_id }}
    ansible.builtin.command: cp /home/{{ ansible_user_id }}/.ssh/authorized_keys {{ home }}/.ssh/authorized_keys
    become: true
    when: option_copy_initial_authorized_keys and check_authorized_keys.stat.exists
    tags:
     - deployer

  - name: Deploy User | Copy authorized_keys from root
    ansible.builtin.command: cp /root/.ssh/authorized_keys {{ home }}/.ssh/authorized_keys
    become: true
    when: option_copy_initial_authorized_keys and ansible_user_id == "root"
    tags:
     - deployer

  - name: Deploy User | Set permission on authorized_keys
    ansible.builtin.file:
      path: "{{ home }}/.ssh/authorized_keys"
      mode: 0600
      owner: "{{ theuser }}"
      group: "{{ thegroup }}"
    become: true
    when: option_copy_initial_authorized_keys and check_authorized_keys.stat.exists
    tags:
     - deployer

  - name: Deploy User | Ensuring sudoers no pwd prompting, if no sudo password set
    ansible.builtin.lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "%{{ theuser }}"
      line: "%{{ theuser }} ALL=(ALL) NOPASSWD:ALL"
      validate: "visudo -cf %s"
    when: thepassword is not defined or thepassword.startswith("__omit_place_holder__")
    become: true
    tags:
     - deployer

  - name: Deploy User | Ensuring sudoers with pwd prompting, if sudo password set
    ansible.builtin.lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "%{{ theuser }}"
      line: "%{{ theuser }} ALL=(ALL) ALL"
      validate: "visudo -cf %s"
    when: thepassword is defined and not thepassword.startswith("__omit_place_holder__")
    become: true
    tags:
     - deployer
