--- # https://github.com/StarterSquad/prudentia/blob/master/prudentia/tasks/ufw.yml
  # Parameters:
  #  ufw_rules_default (provided)
  #  ufw_rules_allow (provided)
  #  ufw_rules_allow_from_hosts (optional)

  - name: UFW | Dependencies
    ansible.builtin.package:
      name: "ufw"
      state: "present"
    become: true
    tags:
      - ufw

  - name: UFW | Reset it
    community.general.ufw:
      state: reset
    become: true
    tags:
      - ufw

  - name: UFW | Configure incoming/outgoing defaults
    community.general.ufw:
      policy: "{{ item.policy }}"
      direction: "{{ item.direction }}"
    with_items: "{{ ufw_rules_default | default([]) }}"
    become: true
    tags:
      - ufw

  - name: UFW | Configure rules to allow incoming traffic
    community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
    with_items: "{{ ufw_rules_allow | default([]) }}"
    when: ufw_rules_allow is defined
    become: true
    tags:
      - ufw

  - name: UFW | Configure rules to allow incoming traffic from specific hosts
    community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
      src: "{{ item.address }}"
    with_items: "{{ ufw_rules_allow_from_hosts | default([]) }}"
    when: ufw_rules_allow_from_hosts is defined
    become: true
    tags:
      - ufw

  - name: UFW | White list hosts
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
    with_items: "{{ whitelistedips | default([]) }}"
    become: true
    tags:
      - ufw

  - name: UFW | Enable it
    community.general.ufw:
      state: enabled
      logging: on
    become: true
    tags:
      - ufw
