- name: Monit | Debian install
  block:

  - name: Monit | Check if is installed
    ansible.builtin.command: dpkg-query -W monit
    when: ansible_os_family == "Debian"
    register: monit_check_deb
    failed_when: monit_check_deb.rc > 1
    changed_when: monit_check_deb.rc == 1
    tags:
      - monit

  - name: Monit | package dependencies
    ansible.builtin.apt:
      pkg:
        - libssl-dev
        - build-essential
      state: present
    become: true
    retries: 3
    register: result
    until: not result.failed
    tags:
      - monit

  - name: Monit | Install from source if deb missing
    when: monit_check_deb.rc == 1 and monit_version != "default"
    block:
      - name: Download openssl-1.0.2-latest.tar.gz
        ansible.builtin.get_url:
          url: https://www.openssl.org/source/openssl-1.0.2p.tar.gz
          dest: /usr/src/openssl-1.0.2p.tar.gz
          mode: "u=rw,g=r,o=r"
        become: true

      - name: Extract openssl-1.0.2-latest.tar.gz
        ansible.builtin.unarchive:
          src: /usr/src/openssl-1.0.2p.tar.gz
          dest: /usr/src/
          remote_src: yes
        become: true

      - name: Monit | ./config
        ansible.builtin.command: ./config
        args:
          chdir: /usr/src/openssl-1.0.2p
        become: true

      - name: Monit | Make
        ansible.builtin.command: make
        args:
          chdir: /usr/src/openssl-1.0.2p
        become: true

      - name: Monit | make install
        ansible.builtin.command: make install
        args:
          chdir: /usr/src/openssl-1.0.2p
        become: true

  - name: Monit | Download
    ansible.builtin.get_url:
      url: "http://us.archive.ubuntu.com/ubuntu/pool/universe/m/monit/monit_{{ monit_version }}_amd64.deb"
      dest: "/tmp/monit_{{ monit_version }}_amd64.deb"
      mode: "u=rw,g=r,o=r"
#                 https://mmonit.com/monit/dist/binary/5.19.0/monit-5.19.0-linux-x64.tar.gz
#                 http://us.archive.ubuntu.com/ubuntu/pool/universe/m/monit/monit_5.19.0-1_amd64.deb
    when: monit_check_deb.rc == 1 and monit_version != "default"
    tags:
      - monit

  - name: Monit | Install (from deb)
    ansible.builtin.apt:
      deb: "/tmp/monit_{{ monit_version }}_amd64.deb"
    when: monit_check_deb.rc == 1 and monit_version != "default"
    become: true
    tags:
      - monit

  - name: Monit | Install (from distribution)
    ansible.builtin.apt:
      pkg: monit
      state: present
      update_cache: true
    when: monit_check_deb.rc == 1 and monit_version == "default"
    retries: 3
    register: result
    until: not result.failed
    become: true
    tags:
      - monit

  when: ansible_os_family == "Debian"

- name: Monit | Install from packages
  block:

  - name: Install monit from packages
    ansible.builtin.package:
      name: "monit"
      state: "present"
    retries: 3
    register: result
    until: not result.failed
    become: true
    tags:
      - monit

  when: ansible_os_family != "Debian"


- name: Monit | Ensure conf dir do exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  with_items:
    - /etc/monit/conf-available
    - /etc/monit/conf-enabled
  become: true
  tags:
    - monit

- name: Monit | Ensure conf.d dir if any, is eliminated
  ansible.builtin.file:
    path: "/etc/monit/conf.d"
    state: "absent"
  with_items:
    - /etc/monit/conf-available
    - /etc/monit/conf-enabled
  become: true
  tags:
    - monit

- name: Monit | Restart
  ansible.builtin.service:
    name: monit
    enabled: "yes"
    state: restarted
  become: true
  when: docker_test is not defined
  tags:
    - monit
    - update
