  - name: SSH | Install fail2ban
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    retries: 3
    register: result
    until: not result.failed
    become: true
    with_items:
      - "{{ fail2ban_packages }}"
    tags:
      - file2ban

  - name: File2Ban | Template ufw action to ban with ufw
    ansible.builtin.template:
      src: "{{ role_dir }}/templates/security/ufw.conf.j2"
      dest: /etc/fail2ban/action.d/ufw.conf
      mode: "u=rw,g=r,o=r"
    when: fail2ban_action == 'ufw' and ansible_os_family == "Debian"
    become: true
    tags:
      - file2ban

  - name: SSH | local fail2ban jail config
    ansible.builtin.template:
      src: "{{ role_dir }}/templates/security/jail.local.j2"
      dest: /etc/fail2ban/jail.local
      mode: "u=rw,g=r,o=r"
    become: true
    tags:
      - file2ban

  - name: SSH |  reload fail2ban
    ansible.builtin.service:
      name: fail2ban
      state: restarted
      enabled: yes
    become: true
    tags:
      - file2ban
