---
- hosts: www
  gather_facts: True

  vars:
    - root_dir: ..

  tasks:

    - ansible.builtin.debug: msg="Tasks section"

    - name:  POC mc install
      ansible.builtin.apt: pkg="mc"
      become: true
