---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
# lint:
#   name: yamllint
platforms:
  - name: xenial
    box: ubuntu/xenial64
    interfaces:
      - network_name: public_network
        type: dhcp
        auto_config: true    
  - name: trusty
    box: ubuntu/trusty64
    interfaces:
      - network_name: public_network
        type: dhcp
        auto_config: true    
  - name: bionic
    box: ubuntu/bionic64
    interfaces:
      - network_name: public_network
        type: dhcp
        auto_config: true    
provisioner:
  name: ansible
  # lint:
  #   name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
