---
dependency:
  name: galaxy
#  requirements_file: tests/requirements.yml

scenario:
  name: default

# lint: |
#        set -e
#        yamllint .
#        ansible-lint
#        flake8

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: jammy
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
    box: ubuntu/jammy64
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network
        type: dhcp
        auto_config: true

#  - name: bionic
#    provider_raw_config_args:
#      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
#    box: ubuntu/bionic64
#    memory: 4096
#    cpus: 2
#    groups:
#      - groupname

    # optional - box is accesible from your real network
#    interfaces:
#      - network_name: private_network
#        type: dhcp
#        auto_config: true


    # interfaces:
    #   - auto_config: true
    #     network_name: private_network
    #     type: dhcp
    #   - virtualbox__intnet: test_network
    #     network_name: private_network
    #     ip: 192.168.0.1
    # provision: false

  # - name: trusty
  #   box: ubuntu/trusty64
  #   # interfaces:
  #   #   - network_name: public_network
  #   #     type: dhcp
  #   #     auto_config: true
  # - name: xenial
  #   box: ubuntu/xenial64
  # - name: bionic
  #   box: ubuntu/bionic64
    # interfaces:
    #   - network_name: public_network
    #     type: dhcp
    #     auto_config: true
    # provider_raw_config_args:
    # - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  # - name: centos6
  #   box: centos/6
  #- name: centos7
  #  box: centos/7
  #- name: centos8
  #  box: centos/8
  # - name: fedora28
  #   box: generic/fedora28
  # - name: alpine
  #   box: generic/alpine28

provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
